FROM python:3.12-slim
WORKDIR /app
COPY ./articles/* /app
COPY ./database_connection.py /app
RUN pip install --no-cache-dir -r requirements.txt
EXPOSE 80
CMD ["python", "-m", "uvicorn", "article_controller:router", "--reload", "--host", "0.0.0.0", "--port", "80"]

