services:
  wikis:
    build:
      dockerfile: Dockerfile_wiki
    ports:
      - "7000:8000"
    depends_on:
      - articles
#    networks:
#      - app-network
  articles:
    build:
      # context: ./article
      dockerfile: Dockerfile_article
    ports:
      - "8000:80"
#   networks:
#     app-network

#networks:
#  app-network:
#    driver: bridge
