FROM python:3.12-slim
WORKDIR /app
COPY ./wiki/* /app
COPY ./database_connection.py /app
RUN pip install --no-cache-dir -r requirements.txt
CMD ["python", "-m", "uvicorn", "wiki_controller:api", "--reload", "--host", "0.0.0.0", "--port", "8000"]

