name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js (if your project uses Node.js)
        uses: actions/setup-node@v2
        with:
          node-version: '22.11.0'

      - name: Install dependencies
        working-directory: app/front_end
        run: npm install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@ec2-13-39-176-208.eu-west-3.compute.amazonaws.com << 'EOF'
            cd /home/ubuntu/laWiki/app/ &&
            source ./aws_stop.sh &&
            export remoterepo="https://illyaro:${{ secrets.ACCESS_TOKEN }}@github.com/illyaro/laWiki.git"
            git pull "$remoterepo" main &&
            sleep 5 &&
            cd front_end &&
            /home/ubuntu/.nvm/versions/node/v22.11.0/bin/npm install &&
            /home/ubuntu/.nvm/versions/node/v22.11.0/bin/npm run clean &&
            /home/ubuntu/.nvm/versions/node/v22.11.0/bin/npm run build &&
            /home/ubuntu/.nvm/versions/node/v22.11.0/bin/npm run start &&
            source ../aws_start.sh
          EOF
        env:
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
